use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct LayoutDefinition {
    #[serde(rename = "friendly-name")]
    friendly_name: String,
    layer: LayerDefinition,
    rows: Vec<RowDefinition>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct LayerDefinition {
    spacing: i32,
    count: i32,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RowDefinition {
    start_position: [i32; 2],
    spacing: [i32; 2],
    bottle_count: i32,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=assets/layout.json");
    println!("cargo:rerun-if-changed=build.rs");

    let layout_json = fs::read_to_string("assets/layout.json")?;
    let layout_definitions: Vec<LayoutDefinition> = serde_json::from_str(&layout_json)?;

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let generated_path = out_dir.join("generated_layouts.rs");

    let mut generated = String::from("// This file is generated by build.rs.\n");
    generated.push_str(&format!(
        "// Parsed {} layout definition(s) from assets/layout.json.\n",
        layout_definitions.len()
    ));

    generated.push_str("impl BottleLayout {\n");
    let mut all_friendly_names = Vec::new();
    for definition in layout_definitions {
        generated.push_str(&format!(
            "    pub fn {}() -> Self {{\n",
            definition.friendly_name.to_lowercase()
        ));

        let rows_macro_argument = definition
            .rows
            .iter()
            .map(|row| {
                let start_pos =
                    format!("Pos({}, {})", row.start_position[0], row.start_position[1]);
                let spacing_pos = format!("Pos({}, {})", row.spacing[0], row.spacing[1]);
                format!("({}, {}, {})", start_pos, spacing_pos, row.bottle_count)
            })
            .collect::<Vec<String>>()
            .join(",");

        generated.push_str(&format!(
            "       bottle_layout!(\"{}\", {}, {}, {})\n",
            definition.friendly_name, definition.layer.spacing, definition.layer.count, rows_macro_argument
        ));

        generated.push_str("    }\n");
        all_friendly_names.push(definition.friendly_name);
    }

    generated.push_str("\n  pub fn get_layouts() -> Vec<Self> {\n");
    generated.push_str("        vec![\n");
    for name in &all_friendly_names {
        generated.push_str(&format!("           Self::{}(),\n", name.to_lowercase()));
    }
    generated.push_str("        ]\n");
    generated.push_str("    }\n");

    generated.push_str("}\n");
    fs::write(generated_path, generated)?;

    Ok(())
}
