use std::{env, fs, path::PathBuf};

const DISCOVERY_MANIFEST_PATH: &str = "../../captures/discovery_levels.json";
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={DISCOVERY_MANIFEST_PATH}");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let generated_path = out_dir.join("generated_level_tests.rs");

    let generated_source = generate_level_test_invocations();
    fs::write(generated_path, generated_source).expect("failed to write generated level tests");
}

fn generate_level_test_invocations() -> String {
    let mut entries = match fs::read_to_string(DISCOVERY_MANIFEST_PATH) {
        Ok(raw) => match serde_json::from_str::<serde_json::Value>(&raw) {
            Ok(parsed) => read_entries(&parsed),
            Err(error) => {
                panic!(
                    "Failed to parse {}: {:?}. Fix the manifest before building tests.",
                    DISCOVERY_MANIFEST_PATH, error
                );
            }
        },
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return "// No discovery captures yet.\n".to_string();
        }
        Err(error) => {
            panic!("Failed to read {}: {:?}", DISCOVERY_MANIFEST_PATH, error);
        }
    };

    entries.sort_by_key(|entry| entry.id);

    let mut output = String::new();
    output.push_str("// Generated by build.rs from captures/discovery_levels.json\n");

    if entries.is_empty() {
        output.push_str("// No discovery captures yet.\n");
        return output;
    }

    for entry in entries.into_iter() {
        output.push_str(&format!(
            "create_generated_test_level!({}, {:?}, {:?}, {:?});\n",
            entry.id, entry.image_filename, entry.expected_bottles, entry.resolved_bottles
        ));
    }

    output
}

#[derive(Debug)]
struct DiscoveryEntry {
    id: u64,
    image_filename: String,
    expected_bottles: String,
    resolved_bottles: String,
}

fn read_entries(value: &serde_json::Value) -> Vec<DiscoveryEntry> {
    let Some(levels) = value.get("levels").and_then(|levels| levels.as_array()) else {
        return Vec::new();
    };

    levels
        .iter()
        .filter_map(|entry| {
            let expected_bottles = entry.get("expected_bottles")?.as_str()?.to_string();
            let resolved_bottles = entry.get("resolved_bottles")?.as_str()?.to_string();

            if expected_bottles.contains('?') && resolved_bottles.contains('?') {
                return None;
            }

            Some(DiscoveryEntry {
                id: entry.get("id")?.as_u64()?,
                image_filename: entry.get("image_filename")?.as_str()?.to_string(),
                expected_bottles,
                resolved_bottles,
            })
        })
        .collect()
}
